[project]
name = "navsim-backend"
version = "0.1.0"
dependencies = [
  "fastapi[standard]",
  "pydantic==2.*",
  "numpy==2.*",
  "python-socketio[asgi]==5.*",
  "redis==5.*",
  "boto3==1.*",
  "uvicorn==0.*"
]
